name: DiscordWebhookPlugin
version: '${project.version}'
main: me.rimon.discordwebhookplugin.DiscordWebhookPlugin
api-version: '1.20'
commands:
  newleaderboard:
    description: Sends a new leaderboard embed to Discord
    usage: /newleaderboard
    permission: DiscordWebhookPlugin.NewLeaderboard
  updateleaderboard:
    description: Updates the existing leaderboard embed on Discord
    usage: /updateleaderboard
    permission: DiscordWebhookPlugin.UpdateLeaderboard
